TableEditor:
  dropdown_threshold: 300
  page_size: 10
  primary_key_delimiter: "_"
  page_sizes: [10, 20, 50, 100]
  full: [admin]
  #menu_classes: [Product, Order, Message, User]
  active_users_interval: 0
  plugins: [ Interchange6, WestBranch ]
  classes:
    Address:
      to_string: |
        join ', ', (
          (join ' ', ($row->first_name, $row->last_name)),
          (join ' ', ($row->address, $row->address_2)),
          (join ' ', ($row->postal_code, $row->city)),
          ($row->state->name),
          ($row->country->name),
        );
    Message:
     # restricted: [admin]
      grid_columns: [messages_id, title, message_types_id, message_type, author_users_id, created, last_modified]
      columns:
        messages_id:
          label: Id
        message_types_id:
          label: Type
        author_users_id:
          label: Author
        approved_by_users_id:
          label: Approved By
        content:
          column_type: html
    MessageType:
      to_string: |
        TableEdit::SchemaInfo::Role::Label::_build_label($row);
    Media:
      columns:
        file:
          upload_dir: Media
    User:
      to_string: "$row->first_name ? $row->first_name . ' '. $row->first_name : $row->username;"
      grid_columns: [users_id, username, email, first_name, last_name, fail_count, created, last_modified, active]
    Product:
      to_string: |
        eval {
           sub r_to_str {
             my $row = shift;
             return r_to_str($row->canonical) . ' > ' .$row->name if ($row->canonical);
             return $row->name;
           };
           my $label = r_to_str($row);
           undef &r_to_str;
           return $label;
         }
      columns:
        description:
          column_type: html
    Navigation:
      to_string: |
        eval {
           sub r_to_str {
             my $row = shift;
             return r_to_str($row->_parent) . ' > ' .$row->uri if ($row->parent_id);
             return $row->uri;
           };
           my $label = r_to_str($row);
           undef &r_to_str;
           return $label;
         }
    Order:
      grid_columns: [orders_id, user, shipping_address, order_date, status]
      to_string: $row->order_number
